version: '3.6'
services:
  app:
    build: ./
    links:
    - database
    volumes:
    - ./www:/var/www
    ports:
    - "3000:80"
    - "4430:443"
  database:
    image: postgres:11
    restart: always
    volumes:
    - ./database:/var/lib/postgresql/data
    environment:
    - POSTGRES_PASSWORD=gENKb9
    - POSTGRES_USER=elevator_control
    - POSTGRES_DB=elevator_control
  adminer:
    image: adminer
    restart: always
    ports:
    - 8000:8080
    links:
    - database