version: '3.6'
services:
  app:
    build: ./
    links:
    - database
    - redis
    volumes:
    - ./www:/var/www
    ports:
    - "3000:80"
    - "9000:9000"
    - "4430:443"
  database:
    image: postgres:11
    restart: always
    environment:    
    - POSTGRES_USER=lift_control
    - POSTGRES_DB=lift_control
    - POSTGRES_PASSWORD=gENKb9
  adminer:
    image: adminer
    restart: always
    ports:
    - 8000:8080
    links:
    - database
  redis:
    image: "redis"